#!/bin/sh

mount proc /proc -t proc
mount sysfs /sys -t sysfs
mount none /sys/kernel/debug -t debugfs


#Create all the symlinks to /bin/busybox
/bin/busybox --install -s

#Create device nodes
#mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s

#cat /proc/partitions
#cat /proc/filesystems


#/sbin/hdparm -tT /dev/mmcblk0
#mount /dev/mmcblk0p1 /mnt
#ls /mnt -la
#cat /mnt/test.txt
#umount /mnt

#cat /proc/cpuinfo
#cat /proc/interrupts

cat /dev/input/event0 > /dev/null &

/bin/sh

#exec switch_root /mnt /sbin/init

